import type { StyleSpecification } from "maplibre-gl";
// Original, restrained cartography using OpenMapTiles vector features.
export const mapStyle: StyleSpecification = {
  version: 8,
  glyphs: "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
  sources: {
    basemap: {
      type: "vector",
      url: "https://tiles.openfreemap.org/planet",
      attribution:
        '<a href="https://openfreemap.org">OpenFreeMap</a> © <a href="https://openmaptiles.org">OpenMapTiles</a> © <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
    },
  },
  light: {
    anchor: "viewport",
    color: "#d2dfef",
    intensity: 0.35,
    position: [1.4, 210, 45],
  },
  layers: [
    {
      id: "background",
      type: "background",
      paint: { "background-color": "#141b22" },
    },
    {
      id: "landcover",
      type: "fill",
      source: "basemap",
      "source-layer": "landcover",
      paint: { "fill-color": "#17272b", "fill-opacity": 0.7 },
    },
    {
      id: "landuse",
      type: "fill",
      source: "basemap",
      "source-layer": "landuse",
      paint: {
        "fill-color": [
          "match",
          ["get", "class"],
          "residential",
          "#222b34",
          "commercial",
          "#252d35",
          "industrial",
          "#20272c",
          "#19292b",
        ],
        "fill-opacity": 0.7,
      },
    },
    {
      id: "water",
      type: "fill",
      source: "basemap",
      "source-layer": "water",
      paint: { "fill-color": "#10191f" },
    },
    {
      id: "aeroway",
      type: "line",
      source: "basemap",
      "source-layer": "aeroway",
      paint: {
        "line-color": "#3c4652",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          1,
          14,
          8,
          17,
          30,
        ],
        "line-opacity": 0.7,
      },
    },
    {
      id: "road-case",
      type: "line",
      source: "basemap",
      "source-layer": "transportation",
      filter: [
        "in",
        ["get", "class"],
        ["literal", ["motorway", "trunk", "primary"]],
      ],
      paint: {
        "line-color": "#141b23",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          2,
          13,
          5,
          16,
          14,
        ],
      },
    },
    {
      id: "roads-small",
      type: "line",
      source: "basemap",
      "source-layer": "transportation",
      filter: [
        "!",
        [
          "in",
          ["get", "class"],
          ["literal", ["motorway", "trunk", "primary", "rail", "path"]],
        ],
      ],
      paint: {
        "line-color": "#3b4652",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          0.2,
          13,
          0.7,
          16,
          3,
        ],
        "line-opacity": 0.72,
      },
    },
    {
      id: "roads-major",
      type: "line",
      source: "basemap",
      "source-layer": "transportation",
      filter: [
        "in",
        ["get", "class"],
        ["literal", ["motorway", "trunk", "primary"]],
      ],
      paint: {
        "line-color": "#596572",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          0.7,
          13,
          2,
          16,
          7,
        ],
        "line-opacity": 0.8,
      },
    },
    {
      id: "building-footprints",
      type: "fill",
      source: "basemap",
      "source-layer": "building",
      minzoom: 12,
      paint: { "fill-color": "#34404b", "fill-opacity": 0.5 },
    },
    {
      id: "buildings-3d",
      type: "fill-extrusion",
      source: "basemap",
      "source-layer": "building",
      minzoom: 12,
      paint: {
        "fill-extrusion-color": "#3b4855",
        "fill-extrusion-height": ["coalesce", ["get", "render_height"], 8],
        "fill-extrusion-base": ["coalesce", ["get", "render_min_height"], 0],
        "fill-extrusion-opacity": 0.75,
      },
    },
    {
      id: "road-labels",
      type: "symbol",
      source: "basemap",
      "source-layer": "transportation_name",
      minzoom: 13,
      layout: {
        "symbol-placement": "line",
        "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
        "text-font": ["Noto Sans Regular"],
        "text-size": 10,
        "text-max-angle": 30,
        "symbol-spacing": 350,
      },
      paint: {
        "text-color": "#7a8b9c",
        "text-halo-color": "#18212b",
        "text-halo-width": 1.5,
      },
    },
    {
      id: "place-labels",
      type: "symbol",
      source: "basemap",
      "source-layer": "place",
      filter: [
        "in",
        ["get", "class"],
        ["literal", ["city", "town", "suburb", "neighbourhood"]],
      ],
      layout: {
        "text-field": [
          "upcase",
          ["coalesce", ["get", "name:en"], ["get", "name"]],
        ],
        "text-font": ["Noto Sans Regular"],
        "text-size": ["match", ["get", "class"], "city", 18, "suburb", 11, 10],
        "text-letter-spacing": 0.17,
        "text-max-width": 10,
      },
      paint: {
        "text-color": "#91a0af",
        "text-halo-color": "#1b242e",
        "text-halo-width": 1.5,
        "text-opacity": 0.8,
      },
    },
  ],
};
